version: "3"

services:
  web:
    build: .
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on: 
      - redis
      - mongodb

  mongodb:
    image: mongodb:latest
    ports:
      - 27017:27017
    volumes:
      - data:/mongodb

  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379

volumes:
  data: